/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.api;

import com.ion.barclaysapi.client.model.AccessDeniedResponse;
import com.ion.barclaysapi.client.model.BadRequestResponse;
import com.ion.barclaysapi.client.model.ErrorResponseBody;
import com.ion.barclaysapi.client.model.NotFoundResponse;
import com.ion.barclaysapi.client.model.TradeBusinessEventsQueryRequest;
import com.ion.barclaysapi.client.model.TradeBusinessEventsQueryResponse;
import com.ion.barclaysapi.client.model.TradeWorkflowStatusResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TradeQueryApiApi
 */
@Ignore
public class TradeQueryApiApiTest {

    private final TradeQueryApiApi api = new TradeQueryApiApi();

    
    /**
     * Get trade business events.
     *
     * Get the trade business events processed at the FMIs.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getBusinessEventsTest() {
        UUID xApiRequestId = null;
        String xParticipantId = null;
        String xFinancialMemberId = null;
        String xApiKey = null;
        TradeBusinessEventsQueryRequest tradeBusinessEventsQueryRequest = null;
        String xSimulationDate = null;
        TradeBusinessEventsQueryResponse response = api.getBusinessEvents(xApiRequestId, xParticipantId, xFinancialMemberId, xApiKey, tradeBusinessEventsQueryRequest, xSimulationDate);

        // TODO: test validations
    }
    
    /**
     * Get trade workflow statuses.
     *
     * Get workflow statuses of the trades processed at the FMIs.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getWorkflowEventsTest() {
        UUID xApiRequestId = null;
        String xParticipantId = null;
        String xFinancialMemberId = null;
        String xApiKey = null;
        String tradeId = null;
        String fmi = null;
        TradeWorkflowStatusResponse response = api.getWorkflowEvents(xApiRequestId, xParticipantId, xFinancialMemberId, xApiKey, tradeId, fmi);

        // TODO: test validations
    }
    
}
