/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.api;

import com.ion.barclaysapi.client.model.AccessDeniedResponse;
import com.ion.barclaysapi.client.model.BadRequestResponse;
import com.ion.barclaysapi.client.model.ClearingRequestBody;
import com.ion.barclaysapi.client.model.ErrorResponseBody;
import com.ion.barclaysapi.client.model.RepoTradeSubmissionResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TradeClearingApiApi
 */
@Ignore
public class TradeClearingApiApiTest {

    private final TradeClearingApiApi api = new TradeClearingApiApi();

    
    /**
     * Submit trade clearing request.
     *
     * Submit the trade request to CCP&#39;s clearing service. &lt;br&gt;&lt;br&gt; Input to this API is a contract formation business event (in CDM format) received from the trade matching service. &lt;br&gt;&lt;br&gt; You can use the Rosetta Technology Portal to understand the specification of a business event
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postSettlementRequest1Test() {
        UUID xApiRequestId = null;
        String xParticipantId = null;
        String xFinancialMemberId = null;
        String xApiKey = null;
        String xSimulationDate = null;
        ClearingRequestBody clearingRequestBody = null;
        RepoTradeSubmissionResponse response = api.postSettlementRequest1(xApiRequestId, xParticipantId, xFinancialMemberId, xApiKey, xSimulationDate, clearingRequestBody);

        // TODO: test validations
    }
    
}
