/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.api;

import com.ion.barclaysapi.client.model.AccessDeniedResponse;
import com.ion.barclaysapi.client.model.BadRequestResponse;
import com.ion.barclaysapi.client.model.ErrorResponseBody;
import com.ion.barclaysapi.client.model.RepoTradeExecutionSubmissionRequest;
import com.ion.barclaysapi.client.model.RepoTradeSubmissionResponse;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TradeExecutionApiApi
 */
@Ignore
public class TradeExecutionApiApiTest {

    private final TradeExecutionApiApi api = new TradeExecutionApiApi();

    
    /**
     * Submit trade execution request.
     *
     * Submit the trade request to the matching service of the trade matching middleware. 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postExecutionRequestTest() {
        UUID xApiRequestId = null;
        String xParticipantId = null;
        String xFinancialMemberId = null;
        String xApiKey = null;
        String xSimulationDate = null;
        RepoTradeExecutionSubmissionRequest repoTradeExecutionSubmissionRequest = null;
        RepoTradeSubmissionResponse response = api.postExecutionRequest(xApiRequestId, xParticipantId, xFinancialMemberId, xApiKey, xSimulationDate, repoTradeExecutionSubmissionRequest);

        // TODO: test validations
    }
    
}
