/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.api;

import com.ion.barclaysapi.client.model.AccessDeniedResponse;
import com.ion.barclaysapi.client.model.BadRequestResponse;
import com.ion.barclaysapi.client.model.ErrorResponseBody;
import com.ion.barclaysapi.client.model.RepoTradeSubmissionResponse;
import com.ion.barclaysapi.client.model.SettlementRequestBody;
import java.util.UUID;
import org.junit.Test;
import org.junit.Ignore;

import java.time.LocalDate;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for TradeSettlementApiApi
 */
@Ignore
public class TradeSettlementApiApiTest {

    private final TradeSettlementApiApi api = new TradeSettlementApiApi();

    
    /**
     * Submit trade settlement request.
     *
     * Submit the trade request to the CSD&#39;s settlement service. &lt;br&gt;&lt;br&gt; Input to this API is a contract formation business event in CDM format. For UC1, it is the business event returned by the trade matching middleware service. For UC2 it is the business events returned by the clearing service. &lt;br&gt;&lt;br&gt; You can use the Rosetta Technology Portal to understand the specification of a business event.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postSettlementRequestTest() {
        UUID xApiRequestId = null;
        String xParticipantId = null;
        String xFinancialMemberId = null;
        String xApiKey = null;
        String xSimulationDate = null;
        SettlementRequestBody settlementRequestBody = null;
        RepoTradeSubmissionResponse response = api.postSettlementRequest(xApiRequestId, xParticipantId, xFinancialMemberId, xApiKey, xSimulationDate, settlementRequestBody);

        // TODO: test validations
    }
    
}
