/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import java.time.OffsetDateTime;
import java.util.Objects;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

/**
 * BusinessEventDto
 */
@JsonPropertyOrder({
  BusinessEventDto.JSON_PROPERTY_BUSINESS_EVENT_NAME,
  BusinessEventDto.JSON_PROPERTY_BUSINESS_EVENT_SEQ,
  BusinessEventDto.JSON_PROPERTY_BUSINESS_EVENT_DATA,
  BusinessEventDto.JSON_PROPERTY_EVENT_CREATED_DATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-25T22:42:46.793138+05:30[Asia/Kolkata]")
public class BusinessEventDto {
  public static final String JSON_PROPERTY_BUSINESS_EVENT_NAME = "businessEventName";
  private String businessEventName;

  public static final String JSON_PROPERTY_BUSINESS_EVENT_SEQ = "businessEventSeq";
  private Integer businessEventSeq;

  public static final String JSON_PROPERTY_BUSINESS_EVENT_DATA = "businessEventData";
  private Object businessEventData;

  public static final String JSON_PROPERTY_EVENT_CREATED_DATE = "eventCreatedDate";
  private OffsetDateTime eventCreatedDate;

  public BusinessEventDto() {
  }

  public BusinessEventDto businessEventName(String businessEventName) {
    
    this.businessEventName = businessEventName;
    return this;
  }

   /**
   * Get businessEventName
   * @return businessEventName
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_EVENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBusinessEventName() {
    return businessEventName;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_EVENT_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessEventName(String businessEventName) {
    this.businessEventName = businessEventName;
  }


  public BusinessEventDto businessEventSeq(Integer businessEventSeq) {
    
    this.businessEventSeq = businessEventSeq;
    return this;
  }

   /**
   * Get businessEventSeq
   * @return businessEventSeq
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_EVENT_SEQ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getBusinessEventSeq() {
    return businessEventSeq;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_EVENT_SEQ)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessEventSeq(Integer businessEventSeq) {
    this.businessEventSeq = businessEventSeq;
  }


  public BusinessEventDto businessEventData(Object businessEventData) {
    
    this.businessEventData = businessEventData;
    return this;
  }

   /**
   * Get businessEventData
   * @return businessEventData
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_EVENT_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getBusinessEventData() {
    return businessEventData;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_EVENT_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessEventData(Object businessEventData) {
    this.businessEventData = businessEventData;
  }


  public BusinessEventDto eventCreatedDate(OffsetDateTime eventCreatedDate) {
    
    this.eventCreatedDate = eventCreatedDate;
    return this;
  }

   /**
   * Get eventCreatedDate
   * @return eventCreatedDate
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EVENT_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  @JsonFormat(shape = JsonFormat.Shape.STRING )
  public OffsetDateTime getEventCreatedDate() {
    return eventCreatedDate;
  }


  @JsonProperty(JSON_PROPERTY_EVENT_CREATED_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEventCreatedDate(OffsetDateTime eventCreatedDate) {
    this.eventCreatedDate = eventCreatedDate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BusinessEventDto businessEventDto = (BusinessEventDto) o;
    return Objects.equals(this.businessEventName, businessEventDto.businessEventName) &&
        Objects.equals(this.businessEventSeq, businessEventDto.businessEventSeq) &&
        Objects.equals(this.businessEventData, businessEventDto.businessEventData) &&
        Objects.equals(this.eventCreatedDate, businessEventDto.eventCreatedDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessEventName, businessEventSeq, businessEventData, eventCreatedDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BusinessEventDto {\n");
    sb.append("    businessEventName: ").append(toIndentedString(businessEventName)).append("\n");
    sb.append("    businessEventSeq: ").append(toIndentedString(businessEventSeq)).append("\n");
    sb.append("    businessEventData: ").append(toIndentedString(businessEventData)).append("\n");
    sb.append("    eventCreatedDate: ").append(toIndentedString(eventCreatedDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

