/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * SettlementRequestBody
 */
@JsonPropertyOrder({
  SettlementRequestBody.JSON_PROPERTY_BUSINESS_EVENT_DATA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-25T22:42:46.793138+05:30[Asia/Kolkata]")
public class SettlementRequestBody {
  public static final String JSON_PROPERTY_BUSINESS_EVENT_DATA = "businessEventData";
  private Object businessEventData;

  public SettlementRequestBody() {
  }

  public SettlementRequestBody businessEventData(Object businessEventData) {
    
    this.businessEventData = businessEventData;
    return this;
  }

   /**
   * Get businessEventData
   * @return businessEventData
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_BUSINESS_EVENT_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Object getBusinessEventData() {
    return businessEventData;
  }


  @JsonProperty(JSON_PROPERTY_BUSINESS_EVENT_DATA)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBusinessEventData(Object businessEventData) {
    this.businessEventData = businessEventData;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SettlementRequestBody settlementRequestBody = (SettlementRequestBody) o;
    return Objects.equals(this.businessEventData, settlementRequestBody.businessEventData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessEventData);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SettlementRequestBody {\n");
    sb.append("    businessEventData: ").append(toIndentedString(businessEventData)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

