/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ion.barclaysapi.client.model.BusinessEventData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TradeBusinessEventsQueryResponse
 */
@JsonPropertyOrder({
  TradeBusinessEventsQueryResponse.JSON_PROPERTY_TRADE_MATCHING_SERVICE,
  TradeBusinessEventsQueryResponse.JSON_PROPERTY_TRADE_CLEARING_SERVICE,
  TradeBusinessEventsQueryResponse.JSON_PROPERTY_TRADE_SETTLEMENT_SERVICE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-25T22:42:46.793138+05:30[Asia/Kolkata]")
public class TradeBusinessEventsQueryResponse {
  public static final String JSON_PROPERTY_TRADE_MATCHING_SERVICE = "tradeMatchingService";
  private List<BusinessEventData> tradeMatchingService;

  public static final String JSON_PROPERTY_TRADE_CLEARING_SERVICE = "tradeClearingService";
  private List<BusinessEventData> tradeClearingService;

  public static final String JSON_PROPERTY_TRADE_SETTLEMENT_SERVICE = "tradeSettlementService";
  private List<BusinessEventData> tradeSettlementService;

  public TradeBusinessEventsQueryResponse() {
  }

  public TradeBusinessEventsQueryResponse tradeMatchingService(List<BusinessEventData> tradeMatchingService) {
    
    this.tradeMatchingService = tradeMatchingService;
    return this;
  }

  public TradeBusinessEventsQueryResponse addTradeMatchingServiceItem(BusinessEventData tradeMatchingServiceItem) {
    if (this.tradeMatchingService == null) {
      this.tradeMatchingService = new ArrayList<>();
    }
    this.tradeMatchingService.add(tradeMatchingServiceItem);
    return this;
  }

   /**
   * Get tradeMatchingService
   * @return tradeMatchingService
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRADE_MATCHING_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BusinessEventData> getTradeMatchingService() {
    return tradeMatchingService;
  }


  @JsonProperty(JSON_PROPERTY_TRADE_MATCHING_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradeMatchingService(List<BusinessEventData> tradeMatchingService) {
    this.tradeMatchingService = tradeMatchingService;
  }


  public TradeBusinessEventsQueryResponse tradeClearingService(List<BusinessEventData> tradeClearingService) {
    
    this.tradeClearingService = tradeClearingService;
    return this;
  }

  public TradeBusinessEventsQueryResponse addTradeClearingServiceItem(BusinessEventData tradeClearingServiceItem) {
    if (this.tradeClearingService == null) {
      this.tradeClearingService = new ArrayList<>();
    }
    this.tradeClearingService.add(tradeClearingServiceItem);
    return this;
  }

   /**
   * Get tradeClearingService
   * @return tradeClearingService
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRADE_CLEARING_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BusinessEventData> getTradeClearingService() {
    return tradeClearingService;
  }


  @JsonProperty(JSON_PROPERTY_TRADE_CLEARING_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradeClearingService(List<BusinessEventData> tradeClearingService) {
    this.tradeClearingService = tradeClearingService;
  }


  public TradeBusinessEventsQueryResponse tradeSettlementService(List<BusinessEventData> tradeSettlementService) {
    
    this.tradeSettlementService = tradeSettlementService;
    return this;
  }

  public TradeBusinessEventsQueryResponse addTradeSettlementServiceItem(BusinessEventData tradeSettlementServiceItem) {
    if (this.tradeSettlementService == null) {
      this.tradeSettlementService = new ArrayList<>();
    }
    this.tradeSettlementService.add(tradeSettlementServiceItem);
    return this;
  }

   /**
   * Get tradeSettlementService
   * @return tradeSettlementService
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRADE_SETTLEMENT_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<BusinessEventData> getTradeSettlementService() {
    return tradeSettlementService;
  }


  @JsonProperty(JSON_PROPERTY_TRADE_SETTLEMENT_SERVICE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradeSettlementService(List<BusinessEventData> tradeSettlementService) {
    this.tradeSettlementService = tradeSettlementService;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradeBusinessEventsQueryResponse tradeBusinessEventsQueryResponse = (TradeBusinessEventsQueryResponse) o;
    return Objects.equals(this.tradeMatchingService, tradeBusinessEventsQueryResponse.tradeMatchingService) &&
        Objects.equals(this.tradeClearingService, tradeBusinessEventsQueryResponse.tradeClearingService) &&
        Objects.equals(this.tradeSettlementService, tradeBusinessEventsQueryResponse.tradeSettlementService);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradeMatchingService, tradeClearingService, tradeSettlementService);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradeBusinessEventsQueryResponse {\n");
    sb.append("    tradeMatchingService: ").append(toIndentedString(tradeMatchingService)).append("\n");
    sb.append("    tradeClearingService: ").append(toIndentedString(tradeClearingService)).append("\n");
    sb.append("    tradeSettlementService: ").append(toIndentedString(tradeSettlementService)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

