/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * TradeBusinessEventsQueryRequest
 */
@JsonPropertyOrder({
  TradeBusinessEventsQueryRequest.JSON_PROPERTY_TRADE_ID,
  TradeBusinessEventsQueryRequest.JSON_PROPERTY_FMI,
  TradeBusinessEventsQueryRequest.JSON_PROPERTY_FROM_DATE,
  TradeBusinessEventsQueryRequest.JSON_PROPERTY_TO_DATE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2023-09-25T22:42:46.793138+05:30[Asia/Kolkata]")
public class TradeBusinessEventsQueryRequest {
  public static final String JSON_PROPERTY_TRADE_ID = "tradeId";
  private String tradeId;

  public static final String JSON_PROPERTY_FMI = "fmi";
  private String fmi;

  public static final String JSON_PROPERTY_FROM_DATE = "fromDate";
  private OffsetDateTime fromDate;

  public static final String JSON_PROPERTY_TO_DATE = "toDate";
  private OffsetDateTime toDate;

  public TradeBusinessEventsQueryRequest() {
  }

  public TradeBusinessEventsQueryRequest tradeId(String tradeId) {
    
    this.tradeId = tradeId;
    return this;
  }

   /**
   * Get tradeId
   * @return tradeId
  **/
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TRADE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTradeId() {
    return tradeId;
  }


  @JsonProperty(JSON_PROPERTY_TRADE_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTradeId(String tradeId) {
    this.tradeId = tradeId;
  }


  public TradeBusinessEventsQueryRequest fmi(String fmi) {
    
    this.fmi = fmi;
    return this;
  }

   /**
   * Get fmi
   * @return fmi
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FMI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getFmi() {
    return fmi;
  }


  @JsonProperty(JSON_PROPERTY_FMI)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFmi(String fmi) {
    this.fmi = fmi;
  }


  public TradeBusinessEventsQueryRequest fromDate(OffsetDateTime fromDate) {
    
    this.fromDate = fromDate;
    return this;
  }

   /**
   * Get fromDate
   * @return fromDate
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_FROM_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getFromDate() {
    return fromDate;
  }


  @JsonProperty(JSON_PROPERTY_FROM_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFromDate(OffsetDateTime fromDate) {
    this.fromDate = fromDate;
  }


  public TradeBusinessEventsQueryRequest toDate(OffsetDateTime toDate) {
    
    this.toDate = toDate;
    return this;
  }

   /**
   * Get toDate
   * @return toDate
  **/
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_TO_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public OffsetDateTime getToDate() {
    return toDate;
  }


  @JsonProperty(JSON_PROPERTY_TO_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setToDate(OffsetDateTime toDate) {
    this.toDate = toDate;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TradeBusinessEventsQueryRequest tradeBusinessEventsQueryRequest = (TradeBusinessEventsQueryRequest) o;
    return Objects.equals(this.tradeId, tradeBusinessEventsQueryRequest.tradeId) &&
        Objects.equals(this.fmi, tradeBusinessEventsQueryRequest.fmi) &&
        Objects.equals(this.fromDate, tradeBusinessEventsQueryRequest.fromDate) &&
        Objects.equals(this.toDate, tradeBusinessEventsQueryRequest.toDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(tradeId, fmi, fromDate, toDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TradeBusinessEventsQueryRequest {\n");
    sb.append("    tradeId: ").append(toIndentedString(tradeId)).append("\n");
    sb.append("    fmi: ").append(toIndentedString(fmi)).append("\n");
    sb.append("    fromDate: ").append(toIndentedString(fromDate)).append("\n");
    sb.append("    toDate: ").append(toIndentedString(toDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

