/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for BusinessEventDto
 */
public class BusinessEventDtoTest {
    private final BusinessEventDto model = new BusinessEventDto();

    /**
     * Model tests for BusinessEventDto
     */
    @Test
    public void testBusinessEventDto() {
        // TODO: test BusinessEventDto
    }

    /**
     * Test the property 'businessEventName'
     */
    @Test
    public void businessEventNameTest() {
        // TODO: test businessEventName
    }

    /**
     * Test the property 'businessEventSeq'
     */
    @Test
    public void businessEventSeqTest() {
        // TODO: test businessEventSeq
    }

    /**
     * Test the property 'businessEventData'
     */
    @Test
    public void businessEventDataTest() {
        // TODO: test businessEventData
    }

    /**
     * Test the property 'eventCreatedDate'
     */
    @Test
    public void eventCreatedDateTest() {
        // TODO: test eventCreatedDate
    }

}
