/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ion.barclaysapi.client.model.RepoBuyer;
import com.ion.barclaysapi.client.model.RepoSeller;
import com.ion.barclaysapi.client.model.RepoTradeDetails;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for RepoTradeExecutionSubmissionRequest
 */
public class RepoTradeExecutionSubmissionRequestTest {
    private final RepoTradeExecutionSubmissionRequest model = new RepoTradeExecutionSubmissionRequest();

    /**
     * Model tests for RepoTradeExecutionSubmissionRequest
     */
    @Test
    public void testRepoTradeExecutionSubmissionRequest() {
        // TODO: test RepoTradeExecutionSubmissionRequest
    }

    /**
     * Test the property 'tradeId'
     */
    @Test
    public void tradeIdTest() {
        // TODO: test tradeId
    }

    /**
     * Test the property 'buyer'
     */
    @Test
    public void buyerTest() {
        // TODO: test buyer
    }

    /**
     * Test the property 'seller'
     */
    @Test
    public void sellerTest() {
        // TODO: test seller
    }

    /**
     * Test the property 'tradeDetails'
     */
    @Test
    public void tradeDetailsTest() {
        // TODO: test tradeDetails
    }

}
