/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for RepoSeller
 */
public class RepoSellerTest {
    private final RepoSeller model = new RepoSeller();

    /**
     * Model tests for RepoSeller
     */
    @Test
    public void testRepoSeller() {
        // TODO: test RepoSeller
    }

    /**
     * Test the property 'sellerName'
     */
    @Test
    public void sellerNameTest() {
        // TODO: test sellerName
    }

    /**
     * Test the property 'sellerLei'
     */
    @Test
    public void sellerLeiTest() {
        // TODO: test sellerLei
    }

    /**
     * Test the property 'sellerAccount'
     */
    @Test
    public void sellerAccountTest() {
        // TODO: test sellerAccount
    }

}
