/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for RepoBuyer
 */
public class RepoBuyerTest {
    private final RepoBuyer model = new RepoBuyer();

    /**
     * Model tests for RepoBuyer
     */
    @Test
    public void testRepoBuyer() {
        // TODO: test RepoBuyer
    }

    /**
     * Test the property 'buyerName'
     */
    @Test
    public void buyerNameTest() {
        // TODO: test buyerName
    }

    /**
     * Test the property 'buyerLei'
     */
    @Test
    public void buyerLeiTest() {
        // TODO: test buyerLei
    }

    /**
     * Test the property 'buyerAccount'
     */
    @Test
    public void buyerAccountTest() {
        // TODO: test buyerAccount
    }

}
