/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for RepoTradeSubmissionResponse
 */
public class RepoTradeSubmissionResponseTest {
    private final RepoTradeSubmissionResponse model = new RepoTradeSubmissionResponse();

    /**
     * Model tests for RepoTradeSubmissionResponse
     */
    @Test
    public void testRepoTradeSubmissionResponse() {
        // TODO: test RepoTradeSubmissionResponse
    }

    /**
     * Test the property 'tradeId'
     */
    @Test
    public void tradeIdTest() {
        // TODO: test tradeId
    }

    /**
     * Test the property 'tradeStatus'
     */
    @Test
    public void tradeStatusTest() {
        // TODO: test tradeStatus
    }

}
