/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.ion.barclaysapi.client.model.BusinessEventData;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for TradeBusinessEventsQueryResponse
 */
public class TradeBusinessEventsQueryResponseTest {
    private final TradeBusinessEventsQueryResponse model = new TradeBusinessEventsQueryResponse();

    /**
     * Model tests for TradeBusinessEventsQueryResponse
     */
    @Test
    public void testTradeBusinessEventsQueryResponse() {
        // TODO: test TradeBusinessEventsQueryResponse
    }

    /**
     * Test the property 'tradeMatchingService'
     */
    @Test
    public void tradeMatchingServiceTest() {
        // TODO: test tradeMatchingService
    }

    /**
     * Test the property 'tradeClearingService'
     */
    @Test
    public void tradeClearingServiceTest() {
        // TODO: test tradeClearingService
    }

    /**
     * Test the property 'tradeSettlementService'
     */
    @Test
    public void tradeSettlementServiceTest() {
        // TODO: test tradeSettlementService
    }

}
