/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for TradeBusinessEventsQueryRequest
 */
public class TradeBusinessEventsQueryRequestTest {
    private final TradeBusinessEventsQueryRequest model = new TradeBusinessEventsQueryRequest();

    /**
     * Model tests for TradeBusinessEventsQueryRequest
     */
    @Test
    public void testTradeBusinessEventsQueryRequest() {
        // TODO: test TradeBusinessEventsQueryRequest
    }

    /**
     * Test the property 'tradeId'
     */
    @Test
    public void tradeIdTest() {
        // TODO: test tradeId
    }

    /**
     * Test the property 'fmi'
     */
    @Test
    public void fmiTest() {
        // TODO: test fmi
    }

    /**
     * Test the property 'fromDate'
     */
    @Test
    public void fromDateTest() {
        // TODO: test fromDate
    }

    /**
     * Test the property 'toDate'
     */
    @Test
    public void toDateTest() {
        // TODO: test toDate
    }

}
