/*
 * Barclays RepoHack 2023 API
 * APIs for the dealers’ and clients’ interactions with financial market infrastructure services (Trade matching middleware, CCPs, CSDs) for the Barclays 2023 Repo Hackathon.<br>Please ensure you include your API key in the `x-api-key` header of your requests.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.ion.barclaysapi.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;

/**
 * Model tests for WorkflowEvent
 */
public class WorkflowEventTest {
    private final WorkflowEvent model = new WorkflowEvent();

    /**
     * Model tests for WorkflowEvent
     */
    @Test
    public void testWorkflowEvent() {
        // TODO: test WorkflowEvent
    }

    /**
     * Test the property 'eventSequence'
     */
    @Test
    public void eventSequenceTest() {
        // TODO: test eventSequence
    }

    /**
     * Test the property 'requestId'
     */
    @Test
    public void requestIdTest() {
        // TODO: test requestId
    }

    /**
     * Test the property 'tradeStatus'
     */
    @Test
    public void tradeStatusTest() {
        // TODO: test tradeStatus
    }

    /**
     * Test the property 'tradeMatchingStatus'
     */
    @Test
    public void tradeMatchingStatusTest() {
        // TODO: test tradeMatchingStatus
    }

    /**
     * Test the property 'eventTimeStamp'
     */
    @Test
    public void eventTimeStampTest() {
        // TODO: test eventTimeStamp
    }

}
